apiVersion: v1
kind: Service
metadata:
  name: rentm-usercenter-service
spec:
  type: NodePort
  selector:
    app: usercenter #这里要和前面对应
  ports:
    - name: usercenter-api-port 
      port: 8888 # 暴露出来访问的端口
      protocol: TCP
      targetPort: 8888 # 目标端口
      nodePort: 30001
    - name: usercenter-rpc-port 
      port: 2004 # 暴露出来访问的端口
      protocol: TCP
      targetPort: 2004 # 目标端口
      nodePort: 30002
    - name: usercenter-mq-port 
      port: 3001 # 暴露出来访问的端口
      protocol: TCP
      targetPort: 3001 # 目标端口
      nodePort: 30003
    - name: aq-cron-cli-port 
      port: 3003 # 暴露出来访问的端口
      protocol: TCP
      targetPort: 3003 # 目标端口
      nodePort: 30004
